### ISSUE TITLE
Status check of PRs is broken

### ISSUE THREAD

**Issue by algomaster99** [hrvey/combine-prs-workflow#9]
Hey! Thanks for the workflow, first of all. I integrated it into https://github.com/SpoonLabs/sorald/ and it worked quite well. However, I had to fix the checking of CI status for each PR in the workflow. The URL [here](https://github.com/hrvey/combine-prs-workflow/blob/master/combine-prs.yml#L54) kept returning `pending` even though I am sure the CI was completed with exit code 0. This has also been reported on [GitHub community forum](https://github.community/t/state-is-pending-statuses-are-missing-with-github-api-v3/14386).

**Comment by mherger** [comment]
@algomaster99 could you please share how you fixed that issue?

**Comment by algomaster99** [comment]
Hi @mherger !

I did something like this:

```diff
if(${{ github.event.inputs.mustBeGreen }}) {
  console.log('Checking green status: ' + branch);
-  const statusResponse = await github.rest.repos.getCombinedStatusForRef({
+  const check_runs = await github.paginate('GET /repos/{owner}/{repo}/commits/{ref}/check-runs', {
    owner: context.repo.owner,
    repo: context.repo.repo,
    ref: branch
  });
- const state = statusResponse['data']['state'];
-  console.log('Validating status: ' + state);
-  if(state != 'success') {
-    console.log('Discarding ' + branch + ' with status ' + state);
-    statusOK = false;
+  for await (const cr of check_runs.data.check_runs) {
+	  console.log('Validating check conclusion: ' + cr.conclusion);
+	  if(cr.conclusion != 'success') {
+	    console.log('Discarding ' + branch + ' with check conclusion ' + cr.conclusion);
+	    statusOK = false;
	  }
}
```

Reference: https://github.com/SpoonLabs/sorald/blob/fd3db17453ace78fca5f8802f2a1cf7c32c780bd/.github/workflows/combine_prs.yml#L78-L95

**Comment by martingjaldbaek** [comment]
Hey, the latest release, 1.3.0, uses a new API that checks the PR/branch status in a way that works both for statuses set with GitHub Actions CI, and external tools. As such this issue should be fixed now. If for any reason it doesn't work for you, let me know!

**Comment by algomaster99** [comment]
Thanks @martingjaldbaek ! I will incorporate the latest changes in our workflow.
